name: CI
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:  
  compile:
    name: "Compile template.tex"
    runs-on: ubuntu-latest
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Compile"
        uses: xu-cheng/latex-action@v3
        with:
          root_file: template.tex
      - name: "Upload PDF"
        uses: actions/upload-artifact@v4
        with:
          name: "Template"
          path: ./template.pdf
          if-no-files-found: error
